name: build

on:
  push:
    tags:
    branches:
  pull_request:

jobs:
  lint:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '~1.23'
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout 5m

          
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: "1.23"
    - name: Test
      run: |
        echo "Testing..."
        go test ./...

