name: release

on:
  push:
    branches:
      - main
    tags:
      - v*


jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23  # Updated to Go version 1.23

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest  # You can specify a version or use "latest"

      - name: Run GoReleaser
        run: goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub provides this token automatically
